In [ ]:
import sys
import os
import pandas as pd 

#use this when run into notebook
sys.path.append(os.path.abspath(".."))

from src.data import DataLoader
from src.sql_utils import sqlData

In [ ]:
# export csv file data
loader = DataLoader()
loader.load_data()

In [3]:
loader_sql = sqlData()
cost_and_demand, wh_data = loader_sql.load_sql_data()
df = pd.merge(cost_and_demand,wh_data[['warehouse','current_supply_unit']],how='left', on='warehouse')
df

,warehouse,Jakarta,Bekasi,Bogor,Depok,Tangerang,Serang,Bandung,Cirebon,Semarang,Solo,Yogyakarta,Surabaya,Malang,Kediri,Jember,current_supply_unit
0,WH-A,7180.0,16764.0,33393.0,19645.0,18378.0,53279.0,82383.0,135525.0,269581.0,309407.0,284761.0,438252.0,441503.0,396861.0,519123.0,210000.0
1,WH-B,267408.0,257820.0,265052.0,268476.0,282900.0,317677.0,205977.0,139997.0,5000.0,57652.0,64689.0,173998.0,179487.0,136209.0,255996.0,145000.0
2,WH-C,436086.0,426506.0,434012.0,437444.0,451603.0,486444.0,374400.0,308995.0,173998.0,145208.0,180245.0,5000.0,56690.0,72649.0,99606.0,120000.0
3,Demand,5886.0,2581.0,2242.0,2304.0,2450.0,1509.0,5906.0,1911.0,4535.0,3428.0,3907.0,5807.0,3177.0,1448.0,1757.0,NaN

In [5]:
from src.optimization import CostTransportation

loader = CostTransportation(df, wh_data)
status, minimum_cost, result_df_opt1 = loader.optimization()

In [6]:
minimum_cost

2039013537.0

In [6]:
from src.sensitivity_cost import SensitivityCost

loader = SensitivityCost(df, wh_data, minimum_cost, min_qty = 200)
status_sensitivity, adjustment_cost, percentage, result_df_opt2 = loader.optimization()

d:\My Dcument\Python Scripts\.venv\Lib\site-packages\pulp\pulp.py:1717: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

In [7]:
status_sensitivity, adjustment_cost, percentage

('Optimal', 3600965537.0, 0.77)

In [8]:
result_df_opt2

   warehouse        city     qty
0       WH-A     Jakarta  5486.0
1       WH-A      Bekasi  2181.0
2       WH-A       Bogor  1842.0
3       WH-A       Depok  1904.0
4       WH-A   Tangerang  2050.0
5       WH-A      Serang  1109.0
6       WH-A     Bandung  5506.0
7       WH-A     Cirebon  1511.0
8       WH-A    Semarang   200.0
9       WH-A        Solo   200.0
10      WH-A  Yogyakarta   200.0
11      WH-A    Surabaya   200.0
12      WH-A      Malang   200.0
13      WH-A      Kediri   200.0
14      WH-A      Jember   200.0
15      WH-B     Jakarta   200.0
16      WH-B      Bekasi   200.0
17      WH-B       Bogor   200.0
18      WH-B       Depok   200.0
19      WH-B   Tangerang   200.0
20      WH-B      Serang   200.0
21      WH-B     Bandung   200.0
22      WH-B     Cirebon   200.0
23      WH-B    Semarang  4135.0
24      WH-B        Solo  3028.0
25      WH-B  Yogyakarta  3507.0
26      WH-B    Surabaya   200.0
27      WH-B      Malang   200.0
28      WH-B      Kediri   200.0
29      WH-B      Jember   200.0
30      WH-C     Jakarta   200.0
31      WH-C      Bekasi   200.0
32      WH-C       Bogor   200.0
33      WH-C       Depok   200.0
34      WH-C   Tangerang   200.0
35      WH-C      Serang   200.0
36      WH-C     Bandung   200.0
37      WH-C     Cirebon   200.0
38      WH-C    Semarang   200.0
39      WH-C        Solo   200.0
40      WH-C  Yogyakarta   200.0
41      WH-C    Surabaya  5407.0
42      WH-C      Malang  2777.0
43      WH-C      Kediri  1048.0
44      WH-C      Jember  1357.0